### ISSUE TITLE
5.1.4 server crash on dependency cycle

### ISSUE THREAD

**Issue by kwpugh** [Azanor/thaumcraft-5#316]
Full crash report: http://pastebin.com/raw/r90ru4qp

A dependency cycle was detected in the input mod set so an ordering cannot be determined
The first mod in the cycle is FMLMod:Botania{r1.8-249}
The mod cycle involves:
	FMLMod:Botania{r1.8-249} : before: [], after: [Baubles, Thaumcraft]
	Dummy Container (AfterAll) @648419316 : before: [], after: []
	FMLMod:Thaumcraft{5.1.4} : before: [], after: [Forge@[11.15.0.1701,), Baubles@[1.1.3.0,)]
	APIContainer{BotaniaAPI:75} : before: [Thaumcraft], after: [Botania]
	Dummy Container (After) @1309116413 : before: [], after: []
net.minecraftforge.fml.common.toposort.ModSortingException: There was a cycle detected in the input graph, sorting is not possible
	at net.minecraftforge.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:190)
	at net.minecraftforge.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199)
	at net.minecraftforge.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199)
	at net.minecraftforge.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199)
	at net.minecraftforge.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199)
	at net.minecraftforge.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199)
	at net.minecraftforge.fml.common.toposort.TopologicalSort.topologicalSort(TopologicalSort.java:145)
	at net.minecraftforge.fml.common.toposort.ModSorter.sort(ModSorter.java:133)
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:271)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:492)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Azanor** [comment]
This was fixed on the Botania side. Get the latest version.
