### ISSUE TITLE
Aura loading problems

### ISSUE THREAD

**Issue by Hyxaru** [Azanor/thaumcraft-5#318]
I closed a world, reloaded it, and suddenly I kept getting a small freeze every second or so. I believe thaumcraft was having issues loading the aura cache. There was a little amount natural nodes nearby, so no node overload.

After restarting minecraft, the issue is 'solved'.

Log part I thought was interresting:
[11:57:18] [Server thread/INFO]: Hyxaru joined the game
[11:57:20] [Client thread/INFO]: [CHAT] WARNING !!!!! This port of Botania is UNOFFICIAL! Do NOT report bugs to Vazkii!!!
[11:57:20] [Client thread/INFO]: [CHAT] Report issues to the porter HERE:https://github.com/williewillus/Botania/issues
[11:57:20] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2359ms behind, skipping 47 tick(s)
[11:57:20] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1014) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1145) ~[bcy.class:?]
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:49) ~[ft.class:?]
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:11) ~[ft.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
	... 9 more
[11:57:20] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1014) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1145) ~[bcy.class:?]
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:49) ~[ft.class:?]
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:11) ~[ft.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
	... 9 more
[11:57:48] [Server thread/INFO]: Saving and pausing game...
[11:57:48] [Server thread/INFO]: Saving chunks for level 'End world'/Overworld
[11:57:52] [Thread-53/WARN] [THAUMCRAFT]: AURAS TAKING 1760 ms LONGER THAN NORMAL
[11:57:54] [Server thread/INFO]: Saving chunks for level 'End world'/Nether
[11:57:54] [Server thread/INFO]: Saving chunks for level 'End world'/The End
[11:58:02] [Thread-53/WARN] [THAUMCRAFT]: AURAS TAKING 9221 ms LONGER THAN NORMAL
[11:58:03] [Server thread/INFO]: Saving chunks for level 'End world'/The Outer Lands
[11:58:12] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2162ms behind, skipping 43 tick(s)

**Comment by runfalk** [comment]
I get the same kinds of warnings on my SMP server. It mostly happens when exploring new chunks, but sometimes it just happens for no apparent reason.  I think it may be Thaumcraft related as that is my only "real" mod.

My full modlist is:

Bagginses-1.8.9-2.1.5b.jar
BetterRain-1.8.9-1.1.0.7BETA.jar
ChunkAnimator-MC1.8.8-1.1.jar
defuzz-1.2.0.jar
DynamicSurroundings-1.8.9-2.0.3.2.jar
ironchest-1.8.9-6.0.121.768.jar
jei_1.8.9-2.22.4.106.jar
JEIAddons_1.8.9-0.10.0.35.jar
journeymap-1.8.8-5.1.3-fairplay.jar
JustEnoughResources-1.8.9-0.3.0.jar
Morpheus-1.8.9-2.0.57.jar
Ping-1.8.9-1.1.2.B11-universal.jar
RoguelikeDungeons-1.8.9-1.4.5.jar
SoundFilters-0.8_for_1.8.jar
Thaumcraft-1.8.9-5.1.4.jar
ThaumicInfusion-1.8.9-4.76.jar
Waila-1.6.0-B3_1.8.8.jar
Wawla-1.4.7-1.8+.jar

I run Forge 1.8.9-11.15.1.1722
