### ISSUE TITLE
Elemental shovel NPE

### ISSUE THREAD

**Issue by sfPlayer1** [Azanor/thaumcraft-5#331]
Version 5.1.4, server side. This involves Tinkers Construct's feature that places the item in the adjacent/right inventory slot on rightclick.

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_66]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_66]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at thaumcraft.common.items.tools.ItemElementalShovel.func_180614_a(ItemElementalShovel.java:136) ~[ItemElementalShovel.class:?]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:718) ~[ForgeHooks.class:?]
        at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:134) ~[zx.class:?]
        at slimeknights.tconstruct.library.utils.ToolHelper.useSecondaryItem(ToolHelper.java:710) ~[ToolHelper.class:?]
        at slimeknights.tconstruct.library.tools.ToolCore.func_180614_a(ToolCore.java:185) ~[ToolCore.class:?]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:718) ~[ForgeHooks.class:?]
        at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:134) ~[zx.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180236_a(ItemInWorldManager.java:439) ~[lg.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:588) ~[lm.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:59) ~[ja.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) ~[ja.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_66]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
        ... 5 more
```

**Comment by sfPlayer1** [comment]
This happens in Thaumcraft.proxy.getFX().drawBlockSparkle(p2, 8401408, 4);, presumable getFX() returns null when running on a dedicated server.

**Comment by bonii-xx** [comment]
Just tested with only the shovel: Also happens if you use it directly
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_40]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_40]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:736) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:365) [DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:681) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.NullPointerException
	at thaumcraft.common.items.tools.ItemElementalShovel.onItemUse(ItemElementalShovel.java:136) ~[ItemElementalShovel.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:720) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:148) ~[ItemStack.class:?]
	at net.minecraft.server.management.ItemInWorldManager.activateBlockOrUseItem(ItemInWorldManager.java:471) ~[ItemInWorldManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processPlayerBlockPlacement(NetHandlerPlayServer.java:617) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.processPacket(C08PacketPlayerBlockPlacement.java:70) ~[C08PacketPlayerBlockPlacement.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.processPacket(C08PacketPlayerBlockPlacement.java:10) ~[C08PacketPlayerBlockPlacement.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_40]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 5 more
```

**Comment by Azanor** [comment]
Yup, it was being called clientside. Already been reported a few times here and the next version will have a fix.
