### ISSUE TITLE
Golems onTaskCompletion() crash

### ISSUE THREAD

**Issue by shadowbolt79** [Azanor/thaumcraft-5#338]
To explain my setup beforehand, I am using Thaumcraft 5.1.4 and Botania.r1.8-248-MC1.8-eb7a6ae, but looking through the error code it doesn't appear to be anything caused by botania? I have about 10 or 12 golems preforming 3 tasks - cutting down and replanting oak trees, using said oak to create and store livingwood, and breaking living rock that's created by a smooth stone generator. It's real fun to see them run around from room to room completing their tasks. However, after about 15min-1h, the server I am running will crash. I am able to reopen the game with seemingly no corruption, making me believe it is a simple tickingEntity() error. Although, when I first had this crash, it required me to update thaumcraft, botania, and forge to even get the server running again, but that was an old version, so I will assume that that was fixed.

`[01:49:57] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) ~[ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
Caused by: java.lang.NullPointerException
        at thaumcraft.common.entities.construct.golem.seals.SealProvide.onTaskCompletion(SealProvide.java:90) ~[SealProvide.class:?]
        at thaumcraft.common.entities.construct.golem.tasks.TaskHandler.completeTask(TaskHandler.java:109) ~[TaskHandler.class:?]
        at thaumcraft.common.entities.construct.golem.ai.AIGoto.func_75246_d(AIGoto.java:117) ~[AIGoto.class:?]
        at thaumcraft.common.entities.construct.golem.ai.AIGotoBlock.func_75246_d(AIGotoBlock.java:23) ~[AIGotoBlock.class:?]
        at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102) ~[re.class:?]
        at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:559) ~[ps.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1775) ~[pr.class:?]
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:382) ~[ps.class:?]
        at thaumcraft.common.entities.construct.golem.EntityThaumcraftGolem.func_70636_d(EntityThaumcraftGolem.java:221) ~[EntityThaumcraftGolem.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1614) ~[pr.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:228) ~[ps.class:?]
        at thaumcraft.common.entities.construct.EntityOwnedConstruct.func_70071_h_(EntityOwnedConstruct.java:83) ~[EntityOwnedConstruct.class:?]
        at thaumcraft.common.entities.construct.golem.EntityThaumcraftGolem.func_70071_h_(EntityThaumcraftGolem.java:233) ~[EntityThaumcraftGolem.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:1860) ~[adm.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:699) ~[le.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1829) ~[adm.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1661) ~[adm.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544) ~[le.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701) ~[MinecraftServer.class:?]
        ... 4 more`

![2016-01-29_14 33 40](https://cloud.githubusercontent.com/assets/7356176/12687409/6e6c311a-c695-11e5-8c97-ebae8c2ac64a.png)
![2016-01-29_14 33 48](https://cloud.githubusercontent.com/assets/7356176/12687411/6e6c8f20-c695-11e5-9db4-d52d11871f4a.png)
![2016-01-29_14 33 27](https://cloud.githubusercontent.com/assets/7356176/12687410/6e6c71b6-c695-11e5-8304-a5cd7c557ce3.png)

**Comment by Azanor** [comment]
Somehow the seal is trying to provide a null itemstack. I'll put in a check to prevent that.
