### ISSUE TITLE
Anvil doesn't work properly & graphical bug

### ISSUE THREAD

**Issue by lenfar** [Azanor/thaumcraft-5#375]
If you craft to enchanted books in the anvil, everything's okay, but if you try to put an enchanted book and a tool together the game crashes.
Also, sometimes the game graphic crashes and remains black... Neither restarting minecraft nor rebooting the whole pc can fix that (not very nice in my survival world -.-). But it's not an graphic card issue because a friend and me had the same problem in the same world with different gc's. 

Best wishes and thank you for that great mod
Lennard

**Comment by MalkContent** [comment]
which enchantments, which tools, mod version numbers?

**Comment by lenfar** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 07.02.16 16:20
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.inventory.ContainerRepair.func_82848_d(ContainerRepair.java:271)
	at net.minecraft.inventory.ContainerRepair.func_75130_a(ContainerRepair.java:142)
	at net.minecraft.inventory.ContainerRepair$1.func_70296_d(ContainerRepair.java:48)
	at net.minecraft.inventory.InventoryBasic.func_70299_a(SourceFile:119)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
	at net.minecraft.inventory.Container.func_75144_a(Container.java:292)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:488)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:629)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:595)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:564)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.inventory.ContainerRepair.func_82848_d(ContainerRepair.java:271)
	at net.minecraft.inventory.ContainerRepair.func_75130_a(ContainerRepair.java:142)
	at net.minecraft.inventory.ContainerRepair$1.func_70296_d(ContainerRepair.java:48)
	at net.minecraft.inventory.InventoryBasic.func_70299_a(SourceFile:119)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
	at net.minecraft.inventory.Container.func_75144_a(Container.java:292)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:488)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:629)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:595)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:564)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiRepair

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['QL_lenfar'/30, l='MpServer', x=-824,30, y=80,00, z=1152,50]]
	Chunk stats: MultiplayerChunkCache: 529, 529
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -184,00,64,00,195,00 - World: (-184,64,195), Chunk: (at 8,4,3 in -12,12; contains blocks -192,0,192 to -177,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3193277 game time, 3111536 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 31 total; [EntityBat['Bat'/65, l='MpServer', x=-803,52, y=36,23, z=1199,40], EntityPig['Pig'/68, l='MpServer', x=-788,88, y=68,00, z=1230,28], EntityCow['Cow'/77, l='MpServer', x=-763,47, y=76,00, z=1145,69], EntityAuraNode['Aura Node'/205, l='MpServer', x=-687,50, y=80,50, z=1065,50], EntityCow['Cow'/78, l='MpServer', x=-757,03, y=77,00, z=1141,06], EntityBat['Bat'/79, l='MpServer', x=-856,75, y=25,59, z=1214,38], EntitySquid['Squid'/80, l='MpServer', x=-852,94, y=50,44, z=1206,75], EntityAuraNode['Aura Node'/212, l='MpServer', x=-686,50, y=85,50, z=1133,50], EntitySquid['Squid'/87, l='MpServer', x=-844,59, y=49,84, z=1203,84], EntityPig['Pig'/90, l='MpServer', x=-772,56, y=71,00, z=1203,59], EntityBat['Bat'/33, l='MpServer', x=-793,25, y=13,10, z=1155,75], EntityBat['Bat'/34, l='MpServer', x=-814,64, y=44,63, z=1197,26], EntityRabbit['Rabbit'/99, l='MpServer', x=-817,53, y=73,00, z=1211,34], EntityBat['Bat'/101, l='MpServer', x=-823,47, y=44,03, z=1223,34], EntityRabbit['Rabbit'/102, l='MpServer', x=-817,28, y=70,00, z=1216,47], EntityAuraNode['Aura Node'/166, l='MpServer', x=-693,50, y=78,50, z=1157,50], EntityAuraNode['Aura Node'/103, l='MpServer', x=-726,50, y=82,50, z=1213,50], EntityBat['Bat'/104, l='MpServer', x=-801,50, y=21,88, z=1076,59], EntityAuraNode['Aura Node'/41, l='MpServer', x=-761,50, y=75,50, z=1187,50], EntityAuraNode['Aura Node'/42, l='MpServer', x=-922,50, y=85,50, z=1053,50], EntityBat['Bat'/43, l='MpServer', x=-867,75, y=27,97, z=1218,25], EntityBat['Bat'/110, l='MpServer', x=-772,39, y=40,78, z=1130,26], EntityCow['Cow'/111, l='MpServer', x=-893,66, y=77,00, z=1165,38], EntitySheep['Sheep'/112, l='MpServer', x=-754,44, y=79,00, z=1085,69], EntityAuraNode['Aura Node'/52, l='MpServer', x=-865,50, y=76,50, z=1061,50], EntityBat['Bat'/53, l='MpServer', x=-857,50, y=18,69, z=1216,25], EntityAuraNode['Aura Node'/118, l='MpServer', x=-952,50, y=84,50, z=1047,50], EntityBat['Bat'/59, l='MpServer', x=-880,25, y=25,25, z=1223,56], EntityAuraNode['Aura Node'/124, l='MpServer', x=-966,50, y=35,50, z=1126,50], EntityPlayerSP['QL_lenfar'/30, l='MpServer', x=-824,30, y=80,00, z=1152,50], EntityRabbit['Rabbit'/61, l='MpServer', x=-746,78, y=82,00, z=1179,09]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 4x Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 349280728 bytes (333 MB) / 824868864 bytes (786 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1734 Optifine OptiFine_1.8.9_HD_U_H2 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1734.jar) 
	UCHIJAAAA	Forge{11.15.1.1734} [Minecraft Forge] (forge-1.8.9-11.15.1.1734.jar) 
	UCHIJAAAA	journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	Thaumcraft{5.1.6} [Thaumcraft] (Thaumcraft-1.8.9-5.1.6.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4248' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1734
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 10.18.15.4248, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz

**Comment by lenfar** [comment]
sword of the zephyr [sharpness 3, repair 2, knockback 1] with enchanted book [knockback 1] in your version 5.1.6

**Comment by lenfar** [comment]
i think it's the newest version?

**Comment by MalkContent** [comment]
I can help with the graphics problem, I think. You have optifine and probably have fboEnable set false in minecraft options.txt; probably so you can use AA. fboEnable true is required for any shaders and shaders happening will give you a black screen. There's a couple of TC debuffs that will add shaders.
You can either set fboEnable back to true or disable TC's shaders in the Thaumcraft.cfg

**Comment by Azanor** [comment]
Unfortunately there is nothing thaumcraft related in that error log. Its seems to be a vanilla issue.
I don't touch the anvil code in any way or form either so I can't really see this being TC related.
