### ISSUE TITLE
When a player placed Smelter Vent to crash the server

### ISSUE THREAD

**Issue by bunSakurAing** [Azanor/thaumcraft-5#506]
When a player placed Smelter Vent, placed in the second to crash the server

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.8.9-1763-3.1.0-BETA-1179.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.0.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 16-3-8 下午6:39
Description: Exception while ticking a block

java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block thaumcraft:smelter_vent, it is not an allowed value
	at net.minecraft.block.state.BlockState$StateImplementation.func_177226_a(BlockState.java:160)
	at thaumcraft.common.blocks.devices.BlockSmelterVent.func_176203_a(BlockSmelterVent.java:66)
	at biomesoplenty.common.handler.AchievementEventHandler.onBlockPlaced(AchievementEventHandler.java:182)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_31_AchievementEventHandler_onBlockPlaced_PlaceEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:81)
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callBlockPlaceEvent(SpongeForgeEventFactory.java:930)
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:316)
	at org.spongepowered.mod.event.SpongeModEventManager.postBulk(SpongeModEventManager.java:220)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:264)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:250)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:127)
	at org.spongepowered.common.event.CauseTracker.handleBlockCaptures(CauseTracker.java:688)
	at org.spongepowered.common.event.CauseTracker.handlePostTickCaptures(CauseTracker.java:445)
	at org.spongepowered.common.event.CauseTracker.updateTickBlock(CauseTracker.java:1038)
	at net.minecraft.world.WorldServer.redirect$onUpdateTick$0(WorldServer.java:133)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:611)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:219)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.func_177226_a(BlockState.java:160)
	at thaumcraft.common.blocks.devices.BlockSmelterVent.func_176203_a(BlockSmelterVent.java:66)
	at biomesoplenty.common.handler.AchievementEventHandler.onBlockPlaced(AchievementEventHandler.java:182)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_31_AchievementEventHandler_onBlockPlaced_PlaceEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:81)
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callBlockPlaceEvent(SpongeForgeEventFactory.java:930)
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:316)
	at org.spongepowered.mod.event.SpongeModEventManager.postBulk(SpongeModEventManager.java:220)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:264)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:250)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:127)
	at org.spongepowered.common.event.CauseTracker.handleBlockCaptures(CauseTracker.java:688)
	at org.spongepowered.common.event.CauseTracker.handlePostTickCaptures(CauseTracker.java:445)
	at org.spongepowered.common.event.CauseTracker.updateTickBlock(CauseTracker.java:1038)
	at net.minecraft.world.WorldServer.redirect$onUpdateTick$0(WorldServer.java:133)

-- Block being ticked --
Details:
	Block: minecraft:unpowered_repeater[delay=4,facing=south,locked=false]
	Block location: World: (159,68,2084), Chunk: (at 15,4,4 in 9,130; contains blocks 144,0,2080 to 159,255,2095), Region: (0,4; contains chunks 0,128 to 31,159, blocks 0,0,2048 to 511,255,2559)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:611)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:219)

-- Affected level --
Details:
	Level name: sc
	All players: 4 total; [EntityPlayerMP['Tomekun'/3228340, l='sc', x=2471.29, y=65.00, z=-1096.96], EntityPlayerMP['wanghui'/3004722, l='sc', x=-10.54, y=72.00, z=-2104.16], EntityPlayerMP['longq'/3318448, l='sc', x=-18.88, y=71.00, z=-2102.24], EntityPlayerMP['OnikawaTatsuya'/3374938, l='sc', x=131.50, y=63.00, z=2072.50]]
	Chunk stats: ServerChunkCache: 889 Drop: 0
	Level seed: 8701121421996264922
	Level generator: ID 10 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: -315.00,72.00,-123.00 - World: (-315,72,-123), Chunk: (at 5,4,5 in -20,-8; contains blocks -320,0,-128 to -305,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 15917868 game time, 8287766 day time
	Level dimension: 5
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 2.6.32-573.7.1.el6.x86_64
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 669745392 bytes (638 MB) / 2997084160 bytes (2858 MB) up to 8432910336 bytes (8042 MB)
	JVM Flags: 4 total; -Xms256M -XX:+UseConcMarkSweepGC -Xmx8192M -XX:MaxPermSize=128M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.19 Powered by Forge 11.15.1.1763 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (paperspigot-1.8.8.jar) 
	UCHIJAAAA	Forge{11.15.1.1763} [Minecraft Forge] (paperspigot-1.8.8.jar) 
	UCHIJAAAA	sponge{1.8.9-1763-3.1.0-BETA-1179} [SpongeForge] (spongeforge-1.8.9-1763-3.1.0-BETA-1179.jar) 
	UCHIJAAAA	AdminShop{1.4} [AdminShop] (AdminShop-1.4.jar) 
	UCHIJAAAA	ArchitectureCraft{1.3.1} [ArchitectureCraft] (ArchitectureCraft-1.3.1-mc1.8.9.jar) 
	UCHIJAAAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1926-universal.jar) 
	UCHIJAAAA	Blood Money{0.2.8} [Blood Money] (BloodMoney.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	Thaumcraft{5.2.0} [Thaumcraft] (Thaumcraft-1.8.9-5.2.0.jar) 
	UCHIJAAAA	Botania{r1.8-250} [Botania] (Botania.r1.8-unofficial-0.6.3.jar) 
	UCHIJAAAA	chiselsandbits{mc1.8.9-v1.8.11} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.11.jar) 
	UCHIJAAAA	CommandSigns{0.9} [CommandSigns] (CommandSigns-0.9b.jar) 
	UCHIJAAAA	customnpcs{1.8.9_beta} [CustomNPCs] (CustomNpcs_1.8.9_beta(21feb16).jar) 
	UCHIJAAAA	EssentialCmds{7.7-9f1b096} [EssentialCmds] (EssentialCmds-7.7.jar) 
	UCHIJAAAA	Explosion Guard{Beta.1.0} [ExplosionGuard] (ExplosionGuard2-0.0.4.jar) 
	UCHIJAAAA	flexiblelogin{0.6} [FlexibleLogin] (FlexibleLogin.jar) 
	UCHIJAAAA	foodcraft{1.2.0} [FoodCraft] (FoodCraft-16.2.4-1.2.2-1.8.9.jar) 
	UCHIJAAAA	journeymap{5.1.3b1} [JourneyMap] (journeymap-1.8.8-5.1.3b1-unlimited.jar) 
	UCHIJAAAA	Keys{1.0} [Keys] (Keys-1.0.1.jar) 
	UCHIJAAAA	TotalEconomy{1.3.2} [Total Economy] (TotalEconomy-v1.3.2.jar) 
	UCHIJAAAA	looty{0.9.0} [RPG Looty] (looty-0-9.jar) 
	UCHIJAAAA	mantle{1.8.9-0.8.2.jenkins95} [Mantle] (Mantle-1.8.9-0.8.2.jar) 
	UCHIJAAAA	MoreFurnaces{1.5.0} [More Furnaces] (morefurnaces-1.5.0-MC1.8.9.jar) 
	UCHIJAAAA	Morpheus{1.8.8-2.0.55} [Morpheus] (Morpheus-1.8.8-2.0.55.jar) 
	UCHIJAAAA	PermissionsEx{2.0-SNAPSHOT} [PermissionsEx] (PermissionsEx-Sponge.jar) 
	UCHIJAAAA	PJW{0.7.53} [Project Worlds] (projectworlds-3.1.0-v0.7.53.jar) 
	UCHIJAAAA	tconstruct{1.8.9-2.1.0.jenkins101} [Tinkers' Construct] (TConstruct-1.8.9-2.1.0.jar) 
	UCHIJAAAA	TreeDestroyage{0.7} [TreeDestroyage] (TreeDestroyage-0.7-19-all.jar) 
	UCHIJAAAA	twentyticks{1.0.0} [Twenty Ticks] (twentyticks.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.8.9-1763-3.1.0-BETA-1179.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.0.jar)
  
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- TinkerDebug (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 4 / 50; [EntityPlayerMP['Tomekun'/3228340, l='sc', x=2471.29, y=65.00, z=-1096.96], EntityPlayerMP['wanghui'/3004722, l='sc', x=-10.54, y=72.00, z=-2104.16], EntityPlayerMP['longq'/3318448, l='sc', x=-18.88, y=71.00, z=-2102.24], EntityPlayerMP['OnikawaTatsuya'/3374938, l='sc', x=131.50, y=63.00, z=2072.50]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)`

**Comment by Azanor** [comment]
This has alread been fixed in 5.2.1
