### ISSUE TITLE
Thaumcraft 5 Crash!!

### ISSUE THREAD

**Issue by OrfeoCL** [Azanor/thaumcraft-5#510]
Minecraft crashes when I have multiples items from thaumcraft, such as centrifuges essence and hungry chests.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 09-03-16 0:23
Description: Exception in world tick

java.lang.NullPointerException: Exception in world tick
	at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:878)
	at net.minecraft.world.World.func_175690_a(World.java:2342)
	at net.minecraft.world.chunk.Chunk.func_150804_b(Chunk.java:1147)
	at net.minecraft.client.multiplayer.ChunkProviderClient.func_73156_b(ChunkProviderClient.java:84)
	at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:110)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2111)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:878)
	at net.minecraft.world.World.func_175690_a(World.java:2342)
	at net.minecraft.world.chunk.Chunk.func_150804_b(Chunk.java:1147)
	at net.minecraft.client.multiplayer.ChunkProviderClient.func_73156_b(ChunkProviderClient.java:84)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['OrfeoCL'/203, l='MpServer', x=90,70, y=60,00, z=91,22]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -140,00,64,00,-92,00 - World: (-140,64,-92), Chunk: (at 4,4,4 in -9,-6; contains blocks -144,0,-96 to -129,255,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 18279389 game time, 24050424 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 82 total; [EntityPig['Cerdo'/25733, l='MpServer', x=36,91, y=64,00, z=152,41], EntityPig['Cerdo'/25735, l='MpServer', x=149,53, y=64,00, z=43,31], EntityHorse['Caballo'/137, l='MpServer', x=43,13, y=67,00, z=31,00], EntityCow['Vaca'/146, l='MpServer', x=58,53, y=67,00, z=33,09], EntityCow['Vaca'/147, l='MpServer', x=58,47, y=67,00, z=34,38], EntityPig['Cerdo'/148, l='MpServer', x=56,91, y=71,00, z=108,22], EntityVillager['Aldeano'/149, l='MpServer', x=93,28, y=78,00, z=70,28], EntityVillager['Aldeano'/150, l='MpServer', x=91,28, y=78,00, z=70,50], EntityAuraNode['Aura Node'/151, l='MpServer', x=104,50, y=79,50, z=65,47], EntityArmorStand['Soporte para armaduras'/152, l='MpServer', x=105,50, y=84,00, z=65,50], EntityArmorStand['Soporte para armaduras'/153, l='MpServer', x=107,50, y=84,00, z=65,50], EntityBat['Murciélago'/42009, l='MpServer', x=20,75, y=12,50, z=151,69], EntityArmorStand['Soporte para armaduras'/154, l='MpServer', x=109,50, y=84,00, z=65,50], EntityThaumcraftGolem['Golem'/155, l='MpServer', x=100,31, y=68,00, z=87,81], EntityArmorStand['Soporte para armaduras'/156, l='MpServer', x=107,50, y=84,00, z=85,50], EntityArmorStand['Soporte para armaduras'/157, l='MpServer', x=105,50, y=84,00, z=85,50], EntityCreeper['Creeper'/43037, l='MpServer', x=77,59, y=64,00, z=159,97], EntityArmorStand['Soporte para armaduras'/158, l='MpServer', x=109,50, y=84,00, z=85,50], EntityZombie['Zombi'/159, l='MpServer', x=71,28, y=10,00, z=60,69], EntityAuraNode['Aura Node'/160, l='MpServer', x=122,47, y=79,50, z=71,50], EntityBat['Murciélago'/41504, l='MpServer', x=31,66, y=20,63, z=111,66], EntityAuraNode['Aura Node'/161, l='MpServer', x=120,50, y=79,50, z=71,50], EntityAuraNode['Aura Node'/162, l='MpServer', x=124,47, y=79,50, z=77,47], EntityAuraNode['Aura Node'/163, l='MpServer', x=118,50, y=79,50, z=79,47], EntityAuraNode['Aura Node'/164, l='MpServer', x=124,47, y=79,50, z=75,50], EntityAuraNode['Aura Node'/165, l='MpServer', x=124,47, y=79,50, z=73,50], EntityAuraNode['Aura Node'/166, l='MpServer', x=118,50, y=79,50, z=71,50], EntityAuraNode['Aura Node'/167, l='MpServer', x=122,47, y=79,50, z=79,47], EntityAuraNode['Aura Node'/168, l='MpServer', x=120,50, y=79,50, z=79,47], EntityItemFrame['entity.ItemFrame.name'/169, l='MpServer', x=121,03, y=71,50, z=69,50], EntityItemFrame['entity.ItemFrame.name'/170, l='MpServer', x=121,03, y=71,50, z=70,50], EntityItemFrame['entity.ItemFrame.name'/171, l='MpServer', x=127,97, y=72,50, z=68,50], EntityMinecartChest['container.minecart'/172, l='MpServer', x=119,50, y=71,06, z=69,50], EntityMinecartChest['container.minecart'/173, l='MpServer', x=119,50, y=71,06, z=70,50], EntityArmorStand['Soporte para armaduras'/174, l='MpServer', x=112,50, y=84,00, z=65,50], EntityPig['Cerdo'/25774, l='MpServer', x=82,13, y=66,00, z=152,81], EntityArmorStand['Soporte para armaduras'/175, l='MpServer', x=114,50, y=84,00, z=65,50], EntityItem['item.item.arrow'/25775, l='MpServer', x=92,63, y=71,00, z=151,28], EntityArmorStand['Soporte para armaduras'/176, l='MpServer', x=116,50, y=84,00, z=65,50], EntityItem['item.item.bone'/25776, l='MpServer', x=91,44, y=70,00, z=151,69], EntityArmorStand['Soporte para armaduras'/177, l='MpServer', x=112,50, y=84,00, z=85,50], EntityArmorStand['Soporte para armaduras'/178, l='MpServer', x=114,50, y=84,00, z=85,50], EntityArmorStand['Soporte para armaduras'/179, l='MpServer', x=116,50, y=84,00, z=85,50], EntityCow['Vaca'/180, l='MpServer', x=74,53, y=70,01, z=32,53], EntityItemFrame['entity.ItemFrame.name'/181, l='MpServer', x=73,97, y=67,50, z=32,50], EntityItemFrame['entity.ItemFrame.name'/182, l='MpServer', x=73,97, y=68,50, z=32,50], EntityCow['Vaca'/183, l='MpServer', x=74,53, y=70,28, z=32,53], EntityCow['Vaca'/184, l='MpServer', x=74,44, y=70,15, z=32,53], EntityCow['Vaca'/185, l='MpServer', x=74,53, y=70,31, z=32,53], EntityCow['Vaca'/186, l='MpServer', x=74,53, y=69,32, z=32,53], EntityCow['Vaca'/187, l='MpServer', x=74,53, y=69,13, z=32,53], EntityCow['Vaca'/188, l='MpServer', x=74,44, y=69,21, z=32,53], EntityCow['Vaca'/189, l='MpServer', x=74,44, y=69,05, z=32,53], EntityCow['Vaca'/190, l='MpServer', x=74,53, y=70,17, z=32,53], EntityBat['Murciélago'/25790, l='MpServer', x=153,75, y=13,19, z=109,28], EntityCow['Vaca'/191, l='MpServer', x=74,44, y=69,09, z=32,53], EntityCow['Vaca'/192, l='MpServer', x=78,47, y=67,00, z=34,75], EntityCow['Vaca'/193, l='MpServer', x=75,44, y=67,00, z=30,47], EntityCow['Vaca'/194, l='MpServer', x=74,44, y=70,00, z=30,44], EntityCow['Vaca'/195, l='MpServer', x=76,53, y=67,00, z=30,50], EntityCow['Vaca'/196, l='MpServer', x=74,44, y=69,35, z=31,42], EntityCow['Vaca'/197, l='MpServer', x=74,53, y=69,13, z=31,44], EntityCow['Vaca'/198, l='MpServer', x=74,44, y=69,82, z=31,48], EntityCow['Vaca'/199, l='MpServer', x=74,53, y=69,00, z=31,50], EntityCow['Vaca'/200, l='MpServer', x=74,44, y=70,44, z=31,50], EntityCow['Vaca'/201, l='MpServer', x=59,00, y=67,00, z=23,00], EntityPig['Cerdo'/205, l='MpServer', x=106,00, y=67,00, z=31,09], EntityPig['Cerdo'/206, l='MpServer', x=20,00, y=64,00, z=110,84], EntitySheep['Oveja'/207, l='MpServer', x=24,00, y=64,00, z=116,94], EntityPig['Cerdo'/208, l='MpServer', x=17,69, y=64,00, z=115,81], EntityPig['Cerdo'/213, l='MpServer', x=130,94, y=69,00, z=26,38], EntityBat['Murciélago'/37599, l='MpServer', x=32,67, y=21,29, z=111,72], EntitySheep['Oveja'/25439, l='MpServer', x=23,19, y=63,00, z=155,84], EntityPig['Cerdo'/25441, l='MpServer', x=28,34, y=64,00, z=147,25], EntityAuraNode['Aura Node'/25448, l='MpServer', x=142,22, y=78,78, z=148,03], EntityPig['Cerdo'/25449, l='MpServer', x=138,97, y=68,00, z=157,47], EntityPlayerSP['OrfeoCL'/203, l='MpServer', x=90,70, y=60,00, z=91,22], EntitySkeleton['Esqueleto'/30831, l='MpServer', x=42,50, y=23,00, z=31,50], EntitySheep['Oveja'/121, l='MpServer', x=25,84, y=66,00, z=16,06], EntityCreeper['Creeper'/124, l='MpServer', x=23,50, y=17,00, z=38,50], EntityCreeper['Creeper'/25468, l='MpServer', x=148,53, y=62,03, z=56,47], EntityPig['Cerdo'/127, l='MpServer', x=24,53, y=32,00, z=99,94]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['OrfeoCL'/203, l='MpServer', x=90,70, y=60,00, z=91,22]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -140,00,64,00,-92,00 - World: (-140,64,-92), Chunk: (at 4,4,4 in -9,-6; contains blocks -144,0,-96 to -129,255,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 18279389 game time, 24050424 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 82 total; [EntityPig['Cerdo'/25733, l='MpServer', x=36,91, y=64,00, z=152,41], EntityPig['Cerdo'/25735, l='MpServer', x=149,53, y=64,00, z=43,31], EntityHorse['Caballo'/137, l='MpServer', x=43,13, y=67,00, z=31,00], EntityCow['Vaca'/146, l='MpServer', x=58,53, y=67,00, z=33,09], EntityCow['Vaca'/147, l='MpServer', x=58,47, y=67,00, z=34,38], EntityPig['Cerdo'/148, l='MpServer', x=56,91, y=71,00, z=108,22], EntityVillager['Aldeano'/149, l='MpServer', x=93,28, y=78,00, z=70,28], EntityVillager['Aldeano'/150, l='MpServer', x=91,28, y=78,00, z=70,50], EntityAuraNode['Aura Node'/151, l='MpServer', x=104,50, y=79,50, z=65,47], EntityArmorStand['Soporte para armaduras'/152, l='MpServer', x=105,50, y=84,00, z=65,50], EntityArmorStand['Soporte para armaduras'/153, l='MpServer', x=107,50, y=84,00, z=65,50], EntityBat['Murciélago'/42009, l='MpServer', x=20,75, y=12,50, z=151,69], EntityArmorStand['Soporte para armaduras'/154, l='MpServer', x=109,50, y=84,00, z=65,50], EntityThaumcraftGolem['Golem'/155, l='MpServer', x=100,31, y=68,00, z=87,81], EntityArmorStand['Soporte para armaduras'/156, l='MpServer', x=107,50, y=84,00, z=85,50], EntityArmorStand['Soporte para armaduras'/157, l='MpServer', x=105,50, y=84,00, z=85,50], EntityCreeper['Creeper'/43037, l='MpServer', x=77,59, y=64,00, z=159,97], EntityArmorStand['Soporte para armaduras'/158, l='MpServer', x=109,50, y=84,00, z=85,50], EntityZombie['Zombi'/159, l='MpServer', x=71,28, y=10,00, z=60,69], EntityAuraNode['Aura Node'/160, l='MpServer', x=122,47, y=79,50, z=71,50], EntityBat['Murciélago'/41504, l='MpServer', x=31,66, y=20,63, z=111,66], EntityAuraNode['Aura Node'/161, l='MpServer', x=120,50, y=79,50, z=71,50], EntityAuraNode['Aura Node'/162, l='MpServer', x=124,47, y=79,50, z=77,47], EntityAuraNode['Aura Node'/163, l='MpServer', x=118,50, y=79,50, z=79,47], EntityAuraNode['Aura Node'/164, l='MpServer', x=124,47, y=79,50, z=75,50], EntityAuraNode['Aura Node'/165, l='MpServer', x=124,47, y=79,50, z=73,50], EntityAuraNode['Aura Node'/166, l='MpServer', x=118,50, y=79,50, z=71,50], EntityAuraNode['Aura Node'/167, l='MpServer', x=122,47, y=79,50, z=79,47], EntityAuraNode['Aura Node'/168, l='MpServer', x=120,50, y=79,50, z=79,47], EntityItemFrame['entity.ItemFrame.name'/169, l='MpServer', x=121,03, y=71,50, z=69,50], EntityItemFrame['entity.ItemFrame.name'/170, l='MpServer', x=121,03, y=71,50, z=70,50], EntityItemFrame['entity.ItemFrame.name'/171, l='MpServer', x=127,97, y=72,50, z=68,50], EntityMinecartChest['container.minecart'/172, l='MpServer', x=119,50, y=71,06, z=69,50], EntityMinecartChest['container.minecart'/173, l='MpServer', x=119,50, y=71,06, z=70,50], EntityArmorStand['Soporte para armaduras'/174, l='MpServer', x=112,50, y=84,00, z=65,50], EntityPig['Cerdo'/25774, l='MpServer', x=82,13, y=66,00, z=152,81], EntityArmorStand['Soporte para armaduras'/175, l='MpServer', x=114,50, y=84,00, z=65,50], EntityItem['item.item.arrow'/25775, l='MpServer', x=92,63, y=71,00, z=151,28], EntityArmorStand['Soporte para armaduras'/176, l='MpServer', x=116,50, y=84,00, z=65,50], EntityItem['item.item.bone'/25776, l='MpServer', x=91,44, y=70,00, z=151,69], EntityArmorStand['Soporte para armaduras'/177, l='MpServer', x=112,50, y=84,00, z=85,50], EntityArmorStand['Soporte para armaduras'/178, l='MpServer', x=114,50, y=84,00, z=85,50], EntityArmorStand['Soporte para armaduras'/179, l='MpServer', x=116,50, y=84,00, z=85,50], EntityCow['Vaca'/180, l='MpServer', x=74,53, y=70,01, z=32,53], EntityItemFrame['entity.ItemFrame.name'/181, l='MpServer', x=73,97, y=67,50, z=32,50], EntityItemFrame['entity.ItemFrame.name'/182, l='MpServer', x=73,97, y=68,50, z=32,50], EntityCow['Vaca'/183, l='MpServer', x=74,53, y=70,28, z=32,53], EntityCow['Vaca'/184, l='MpServer', x=74,44, y=70,15, z=32,53], EntityCow['Vaca'/185, l='MpServer', x=74,53, y=70,31, z=32,53], EntityCow['Vaca'/186, l='MpServer', x=74,53, y=69,32, z=32,53], EntityCow['Vaca'/187, l='MpServer', x=74,53, y=69,13, z=32,53], EntityCow['Vaca'/188, l='MpServer', x=74,44, y=69,21, z=32,53], EntityCow['Vaca'/189, l='MpServer', x=74,44, y=69,05, z=32,53], EntityCow['Vaca'/190, l='MpServer', x=74,53, y=70,17, z=32,53], EntityBat['Murciélago'/25790, l='MpServer', x=153,75, y=13,19, z=109,28], EntityCow['Vaca'/191, l='MpServer', x=74,44, y=69,09, z=32,53], EntityCow['Vaca'/192, l='MpServer', x=78,47, y=67,00, z=34,75], EntityCow['Vaca'/193, l='MpServer', x=75,44, y=67,00, z=30,47], EntityCow['Vaca'/194, l='MpServer', x=74,44, y=70,00, z=30,44], EntityCow['Vaca'/195, l='MpServer', x=76,53, y=67,00, z=30,50], EntityCow['Vaca'/196, l='MpServer', x=74,44, y=69,35, z=31,42], EntityCow['Vaca'/197, l='MpServer', x=74,53, y=69,13, z=31,44], EntityCow['Vaca'/198, l='MpServer', x=74,44, y=69,82, z=31,48], EntityCow['Vaca'/199, l='MpServer', x=74,53, y=69,00, z=31,50], EntityCow['Vaca'/200, l='MpServer', x=74,44, y=70,44, z=31,50], EntityCow['Vaca'/201, l='MpServer', x=59,00, y=67,00, z=23,00], EntityPig['Cerdo'/205, l='MpServer', x=106,00, y=67,00, z=31,09], EntityPig['Cerdo'/206, l='MpServer', x=20,00, y=64,00, z=110,84], EntitySheep['Oveja'/207, l='MpServer', x=24,00, y=64,00, z=116,94], EntityPig['Cerdo'/208, l='MpServer', x=17,69, y=64,00, z=115,81], EntityPig['Cerdo'/213, l='MpServer', x=130,94, y=69,00, z=26,38], EntityBat['Murciélago'/37599, l='MpServer', x=32,67, y=21,29, z=111,72], EntitySheep['Oveja'/25439, l='MpServer', x=23,19, y=63,00, z=155,84], EntityPig['Cerdo'/25441, l='MpServer', x=28,34, y=64,00, z=147,25], EntityAuraNode['Aura Node'/25448, l='MpServer', x=142,22, y=78,78, z=148,03], EntityPig['Cerdo'/25449, l='MpServer', x=138,97, y=68,00, z=157,47], EntityPlayerSP['OrfeoCL'/203, l='MpServer', x=90,70, y=60,00, z=91,22], EntitySkeleton['Esqueleto'/30831, l='MpServer', x=42,50, y=23,00, z=31,50], EntitySheep['Oveja'/121, l='MpServer', x=25,84, y=66,00, z=16,06], EntityCreeper['Creeper'/124, l='MpServer', x=23,50, y=17,00, z=38,50], EntityCreeper['Creeper'/25468, l='MpServer', x=148,53, y=62,03, z=56,47], EntityPig['Cerdo'/127, l='MpServer', x=24,53, y=32,00, z=99,94]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 7 (amd64) version 6.1
	CPU: 4x AMD A6-3400M APU with Radeon(tm) HD Graphics
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 463264056 bytes (441 MB) / 926068736 bytes (883 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP 9.19 Powered by Forge 11.15.1.1763 Optifine OptiFine_1.8.9_HD_U_H2 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1763.jar) 
	UCHIJAAAA	Forge{11.15.1.1763} [Minecraft Forge] (forge-1.8.9-11.15.1.1763.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	Thaumcraft{5.2.1} [Thaumcraft] (Thaumcraft-1.8.9-5.2.1.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.1.10600 Compatibility Profile Context' Renderer: 'AMD Radeon(TM) HD 6520G'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1763
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) HD 6520G GL version 4.1.10600 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Español (México)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A6-3400M APU with Radeon(tm) HD Graphics

![2016-03-09_00 37 52](https://cloud.githubusercontent.com/assets/17734425/13624658/7cef7886-e586-11e5-983a-4056a09de5cd.png)
![2016-03-09_00 36 41](https://cloud.githubusercontent.com/assets/17734425/13624659/7cfc17e4-e586-11e5-9237-20e066923211.png)
![2016-03-09_00 36 51](https://cloud.githubusercontent.com/assets/17734425/13624660/7cff30d2-e586-11e5-9c75-17b991a9fa40.png)

**Comment by Azanor** [comment]
Unfortunately the error report makes no mention of TC so I have no way of tracking the cause of the issue.
