### ISSUE TITLE
NoSuchFieldError while running 5.0.2 deobf under Idea

### ISSUE THREAD

**Issue by ZeroNoRyouki** [Azanor/thaumcraft-5#55]
Hi, I'm playing around with the TC API and today I've switched to your last dev build of the mod and now the game crash during pre-initialization because of a NoSuchFieldError exception

Here is the complete stack trace:

java.lang.NoSuchFieldError: smelterVent
	at thaumcraft.common.config.ConfigBlocks.initializeBlocks(ConfigBlocks.java:262) ~[Thaumcraft-deobf-1.8-5.0.2.jar:?]
	at thaumcraft.common.config.ConfigBlocks.init(ConfigBlocks.java:160) ~[Thaumcraft-deobf-1.8-5.0.2.jar:?]
	at thaumcraft.common.Thaumcraft.preInit(Thaumcraft.java:164) ~[Thaumcraft-deobf-1.8-5.0.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:537) ~[forgeSrc-1.8-11.14.3.1543.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forgeSrc-1.8-11.14.3.1543.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forgeSrc-1.8-11.14.3.1543.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:550) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:249) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:446) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:356) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:117) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
	at GradleStart.main(Unknown Source) [start/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:?]

All was working fine with 5.0.1

Z

PS: I switched to 5.0.2 manly because I noticed a possible bug in your hud handler: when I put a chargable item in the wand pedestal (say, a vis amulet) it keep showing the aspect at zero while in really they were recharging

**Comment by Azanor** [comment]
It looks like you didn't switch to the new API in your code. The missing field is one that was added to the api.

**Comment by ZeroNoRyouki** [comment]
You are correct, indeed

I've run a diff yesterday against my copy of the API and your zip file but I guess I missed some changes.... Now I'm a bit puzzled, I was under the impression that FML would prevent a mod to put in play an old version of the API since you used the @API annotation (and the version reported by my copy is older the the one reported in your jar)

I've re-checked the charging problem and I can confirm that when I put an empty IRechargable item in the Recharge Pedestal, your hud handler display 0 as the amount of aspect contained in the item even if the item is recharging itself. If I take out the same item mid-charge and put it back in the Pedestal I get the correct display, with the values updating while the charging is in progess

**Comment by ZeroNoRyouki** [comment]
I think I've partialy figured out what's going on: it's a client/server synchronization (or lack of) issue

The Recharge Pedestal TE call IRechargable::handleRecharge only on the server thread so the client side item(stack) is never recharged (and never get an nbt tag). Your hud handler is actually correct in always reporting a zero-charge status

Things get worse when you remove a partially charged item from the Pedestal.

While the item is still in the Pedestal I have an itemstack with a correct nbt tag on the server "side" and an itemstack with no nbt tag on the client "side"

When I remove the item and then put it back in the Pedestal I end up with a new itemstack with a correct nbt tag on the server and a new itemstack on the client that reference the same nbt tag instance held by the server itemstack... It look like that when the integrated server synchronize the the player inventory when I recover the item from the Pedestal, it creates the client side itemstack by just using the existing nbt tag of the server side itemstack without coping it. So now the hud handler is actually reading the server side nbt tag that is being updated on the server side and so we get the "charging" feedback on the client

I've just started modding so I don't known if what I think MC is doing is correct or expected behavior. I've not tested it on the dedicated server but since there is no object sharing there I guess that the hud will keep displaying a fixed value

**Comment by Azanor** [comment]
Yeah, I have the code in place to sync the itemstacks, but it seems during the migration to 1.8 I removed the call to them :/
