### ISSUE TITLE
errors on the log

### ISSUE THREAD

**Issue by jochuan** [Azanor/thaumcraft-5#572]
i am getting these errors on the log on the latest forge and mod version on 1.8.9

OptiFine] Scaled too small texture: minecraft:blocks/dispenser_front_horizontal, 8 -> 16
[OptiFine] Scaled too small texture: minecraft:blocks/grass_side_overlay, 8 -> 16
[OptiFine] Scaled too small texture: minecraft:blocks/hardened_clay_stained_red, 8 -> 16
[16:39:50] [Client thread/INFO]: Created: 1024x1024 textures-atlas
[16:39:53] [Client thread/INFO] [STDOUT]: [pokecube.modelloader.ModPokecubeML:loadModels:95]: Loading Pokemob Models
[16:40:07] [Client thread/ERROR] [FML]: Exception loading model for variant thaumcraft:barrier#normal
java.lang.Exception: Could not load model definition for variant thaumcraft:barrier#normal
	at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:211) ~[ModelLoader.class:?]
	at net.minecraft.client.resources.model.ModelBakery.func_177591_a(ModelBakery.java:109) ~[bot.class:?]
	at net.minecraftforge.client.model.ModelLoader.loadBlocks(ModelLoader.java:166) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:111) ~[ModelLoader.class:?]
	at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:28) [bou.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130) [bnn.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111) [bnn.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:732) [ave.class:?]
	at com.mumfrey.liteloader.client.ResourcesClient.refreshResources(ResourcesClient.java:40) [ResourcesClient.class:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at com.mumfrey.liteloader.client.LiteLoaderEventBrokerClient.onStartupComplete(LiteLoaderEventBrokerClient.java:259) [LiteLoaderEventBrokerClient.class:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at com.mumfrey.liteloader.client.ClientProxy.onStartupComplete(ClientProxy.java:48) [ClientProxy.class:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.client.Minecraft.handler$onStartupComplete$0(Minecraft.java:37) [ave.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Encountered an exception when loading model definition of model thaumcraft:blockstates/barrier.json
	at net.minecraft.client.resources.model.ModelBakery.func_177586_a(ModelBakery.java:165) ~[bot.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:207) ~[ModelLoader.class:?]
	... 20 more
Caused by: java.io.FileNotFoundException: thaumcraft:blockstates/barrier.json
	at net.minecraft.client.resources.FallbackResourceManager.func_135056_b(FallbackResourceManager.java:93) ~[bnb.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_135056_b(SimpleReloadableResourceManager.java:78) ~[bnn.class:?]
	at net.minecraft.client.resources.model.ModelBakery.func_177586_a(ModelBakery.java:143) ~[bot.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:207) ~[ModelLoader.class:?]
	... 20 more
[16:40:07] [Client thread/ERROR] [FML]: Model definition for location thaumcraft:eldritch#type=teleporter not found
[16:40:07] [Client thread/ERROR] [FML]: Model definition for location thaumcraft:eldritch#type=lock not found
[16:40:07] [Client thread/ERROR] [FML]: Model definition for location thaumcraft:leaf#inventory not found
[16:40:07] [Client thread/ERROR] [FML]: Suppressed additional 9 model loading errors for domain thaumcraft
[16:40:07] [Client thread/INFO] [LiteLoader]: Calling late init for mod Presence Footsteps
[16:40:09] [Client thread/INFO] [STDOUT]: [eu.ha3.presencefootsteps.log.PFLog:log:26]: [PF]: Resource Pack reload detected...
[16:40:09] [Client thread/INFO] [LiteLoader]: Calling late init for mod VoxelMap
[16:40:11] [Client thread/WARN] [FML]: =============================================================
[16:40:11] [Client thread/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[16:40:11] [Client thread/WARN] [FML]: Offendor: com/thevoxelbox/voxelmap/c/h.if()V
[16:40:11] [Client thread/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[16:40:11] [Client thread/WARN] [FML]: =============================================================
[16:40:11] [Client thread/WARN] [FML]: =============================================================
[16:40:11] [Client thread/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[16:40:11] [Client thread/WARN] [FML]: Offendor: com/thevoxelbox/voxelmap/c/h.for()V
[16:40:11] [Client thread/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[16:40:11] [Client thread/WARN] [FML]: =============================================================
[16:40:17] [Client thread/INFO] [com.thevoxelbox.voxelmap.c.h]: Created: 256x128 waypoints-atlas
[16:40:18] [Client thread/INFO] [com.thevoxelbox.voxelmap.c.h]: Created: 128x128 chooser-atlas
[16:40:28] [Client thread/INFO] [com.thevoxelbox.voxelmap.c.h]: Created: 1024x512 mobs-atlas
[16:40:29] [Client thread/INFO] [LiteLoader]: Baking listener list for ViewportListener with 0 listeners
[16:40:29] [Client thread/INFO] [LiteLoader]: Sound handler reload inhibit removed
[16:40:29] [Client thread/INFO] [LiteLoader]: Reloading sound handler
[16:40:29] [Client thread/INFO]: SoundSystem shutting down...
[16:40:31] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[16:40:31] [Sound Library Loader/INFO]: Starting up SoundSystem...

**Comment by Azanor** [comment]
Just a side effect of the new modelling system. Perfectly ignorable.
