### ISSUE TITLE
[TC6 BETA3] Research Table crash w/ Crimson Rites 

### ISSUE THREAD

**Issue by VocableWAZZAM** [Azanor/thaumcraft-5#663]
Whenever I get(and select) the research option that uses the crimson rites book, leave the research table, then interact the research table the game crashed. The only solution I could find for this was to break the research table then replace it, though of course the crimson rites book is lost along with any other research that was earned.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 1/27/18 11:12 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at thaumcraft.client.gui.GuiResearchTable.func_146976_a(GuiResearchTable.java:400)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:76)
	at thaumcraft.client.gui.GuiResearchTable.func_73863_a(GuiResearchTable.java:108)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thaumcraft.client.gui.GuiResearchTable.func_146976_a(GuiResearchTable.java:400)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:76)
	at thaumcraft.client.gui.GuiResearchTable.func_73863_a(GuiResearchTable.java:108)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: thaumcraft.client.gui.GuiResearchTable
	Mouse location: Scaled: (480, 254). Absolute: (960, 509)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1018). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['VocableWAZZAM'/339, l='MpServer', x=5.63, y=64.00, z=243.29]]
	Chunk stats: MultiplayerChunkCache: 1089, 1089
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (48,64,256), Chunk: (at 0,4,0 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 708846 game time, 1132099 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 100 total; [EntityCreeper['Creeper'/54, l='MpServer', x=-71.50, y=38.00, z=164.50], EntityZombie['Zombie'/56, l='MpServer', x=-69.50, y=19.00, z=229.50], EntitySheep['Sheep'/57, l='MpServer', x=-72.58, y=69.57, z=276.85], EntitySheep['Sheep'/58, l='MpServer', x=-68.47, y=72.00, z=280.03], EntityBat['Bat'/69, l='MpServer', x=-52.75, y=13.03, z=193.25], EntityCreeper['Creeper'/70, l='MpServer', x=-61.50, y=77.00, z=177.50], EntitySheep['Sheep'/71, l='MpServer', x=-52.43, y=78.00, z=197.30], EntitySheep['Sheep'/72, l='MpServer', x=-53.51, y=76.00, z=214.27], EntitySheep['Sheep'/73, l='MpServer', x=-51.19, y=73.00, z=213.16], EntityCreeper['Creeper'/74, l='MpServer', x=-56.63, y=48.00, z=235.30], EntityZombie['Zombie'/75, l='MpServer', x=-55.50, y=50.00, z=230.78], EntitySheep['Sheep'/76, l='MpServer', x=-61.21, y=70.00, z=279.55], EntitySheep['Sheep'/77, l='MpServer', x=-52.47, y=90.00, z=316.73], EntitySheep['Sheep'/78, l='MpServer', x=-56.81, y=87.00, z=319.47], EntityCreeper['Creeper'/90, l='MpServer', x=-37.50, y=23.00, z=168.50], EntitySkeleton['Skeleton'/91, l='MpServer', x=-46.27, y=21.00, z=175.51], EntitySkeleton['Skeleton'/92, l='MpServer', x=-34.50, y=19.00, z=216.50], EntityZombie['Zombie'/93, l='MpServer', x=-40.65, y=36.00, z=213.83], EntityBat['Bat'/94, l='MpServer', x=-44.57, y=38.68, z=242.52], EntitySheep['Sheep'/95, l='MpServer', x=-33.84, y=64.00, z=266.22], EntitySheep['Sheep'/96, l='MpServer', x=-38.82, y=64.00, z=292.59], EntitySkeleton['Skeleton'/102, l='MpServer', x=-22.50, y=38.00, z=229.50], EntityZombie['Zombie'/103, l='MpServer', x=-16.79, y=38.00, z=231.44], EntityCreeper['Creeper'/104, l='MpServer', x=-17.50, y=30.00, z=241.50], EntityZombie['Zombie'/105, l='MpServer', x=-25.18, y=32.00, z=249.50], EntityZombie['Zombie'/106, l='MpServer', x=-22.50, y=33.00, z=257.50], EntityZombie['Zombie'/107, l='MpServer', x=-26.62, y=31.23, z=253.53], EntityBat['Bat'/108, l='MpServer', x=-13.25, y=32.07, z=263.70], EntitySkeleton['Skeleton'/109, l='MpServer', x=-18.50, y=29.00, z=309.50], EntityPlayerSP['VocableWAZZAM'/339, l='MpServer', x=5.63, y=64.00, z=243.29], EntityPig['Pig'/120, l='MpServer', x=-12.49, y=71.00, z=170.67], EntitySkeleton['Skeleton'/121, l='MpServer', x=-6.50, y=39.00, z=231.50], EntityCreeper['Creeper'/122, l='MpServer', x=-11.50, y=19.00, z=251.50], EntitySpider['Spider'/123, l='MpServer', x=-5.38, y=38.00, z=250.09], EntitySpider['Spider'/124, l='MpServer', x=-4.01, y=39.00, z=246.70], EntityCreeper['Creeper'/125, l='MpServer', x=-6.50, y=32.00, z=241.50], EntityZombie['Zombie'/126, l='MpServer', x=-12.50, y=31.00, z=266.50], EntityBat['Bat'/127, l='MpServer', x=-7.40, y=38.03, z=252.53], EntityCreeper['Creeper'/128, l='MpServer', x=-13.50, y=40.00, z=322.50], EntitySheep['Sheep'/135, l='MpServer', x=10.49, y=69.00, z=181.81], EntitySheep['Sheep'/136, l='MpServer', x=14.35, y=70.00, z=187.95], EntityPig['Pig'/137, l='MpServer', x=5.79, y=72.00, z=181.32], EntityCreeper['Creeper'/138, l='MpServer', x=0.50, y=33.00, z=223.50], EntityBat['Bat'/139, l='MpServer', x=16.49, y=39.66, z=219.48], EntityZombie['Zombie'/140, l='MpServer', x=8.20, y=39.00, z=244.30], EntitySquid['Squid'/141, l='MpServer', x=11.65, y=62.10, z=227.02], EntitySquid['Squid'/142, l='MpServer', x=21.04, y=62.00, z=229.60], EntitySkeleton['Skeleton'/143, l='MpServer', x=7.61, y=39.00, z=244.89], EntitySpider['Spider'/144, l='MpServer', x=5.14, y=40.00, z=245.58], EntitySkeleton['Skeleton'/145, l='MpServer', x=16.50, y=30.00, z=305.78], EntityBat['Bat'/659, l='MpServer', x=-39.70, y=26.03, z=261.71], EntityBat['Bat'/660, l='MpServer', x=-37.95, y=26.23, z=267.64], EntityBat['Bat'/662, l='MpServer', x=-40.72, y=26.29, z=265.72], EntitySheep['Sheep'/158, l='MpServer', x=35.27, y=72.00, z=165.31], EntitySheep['Sheep'/159, l='MpServer', x=18.51, y=71.00, z=180.45], EntitySheep['Sheep'/160, l='MpServer', x=24.50, y=71.00, z=196.24], EntityZombie['Zombie'/161, l='MpServer', x=24.50, y=43.00, z=232.23], EntityBat['Bat'/162, l='MpServer', x=18.68, y=38.10, z=234.75], EntitySkeleton['Skeleton'/163, l='MpServer', x=24.50, y=44.00, z=233.50], EntitySkeleton['Skeleton'/164, l='MpServer', x=27.50, y=35.00, z=238.50], EntityCreeper['Creeper'/165, l='MpServer', x=18.45, y=30.00, z=245.01], EntitySkeleton['Skeleton'/166, l='MpServer', x=19.50, y=32.00, z=254.50], EntityZombie['Zombie'/167, l='MpServer', x=19.48, y=36.00, z=244.25], EntityZombie['Zombie'/168, l='MpServer', x=16.59, y=31.00, z=258.83], EntitySheep['Sheep'/175, l='MpServer', x=39.55, y=74.00, z=163.33], EntitySheep['Sheep'/176, l='MpServer', x=38.23, y=73.00, z=181.52], EntitySheep['Sheep'/177, l='MpServer', x=41.47, y=69.00, z=198.36], EntitySheep['Sheep'/178, l='MpServer', x=34.78, y=65.00, z=199.62], EntitySheep['Sheep'/179, l='MpServer', x=42.51, y=65.00, z=201.73], EntityCreeper['Creeper'/180, l='MpServer', x=42.42, y=56.00, z=223.19], EntitySkeleton['Skeleton'/181, l='MpServer', x=32.50, y=41.00, z=262.50], EntitySkeleton['Skeleton'/182, l='MpServer', x=32.50, y=41.00, z=262.50], EntitySkeleton['Skeleton'/183, l='MpServer', x=38.50, y=52.00, z=284.50], EntityCow['Cow'/184, l='MpServer', x=42.47, y=65.00, z=298.15], EntityChicken['Chicken'/185, l='MpServer', x=35.90, y=68.00, z=313.49], EntityChicken['Chicken'/186, l='MpServer', x=32.79, y=68.00, z=309.48], EntityBat['Bat'/196, l='MpServer', x=56.25, y=56.03, z=172.50], EntityBat['Bat'/197, l='MpServer', x=59.79, y=56.76, z=166.79], EntitySheep['Sheep'/198, l='MpServer', x=49.81, y=77.00, z=182.50], EntitySheep['Sheep'/199, l='MpServer', x=57.41, y=76.00, z=191.45], EntitySheep['Sheep'/200, l='MpServer', x=61.22, y=74.00, z=198.51], EntityCreeper['Creeper'/201, l='MpServer', x=54.50, y=15.00, z=269.50], EntitySheep['Sheep'/202, l='MpServer', x=59.23, y=71.00, z=299.28], EntitySheep['Sheep'/203, l='MpServer', x=53.20, y=71.00, z=300.44], EntityVillager['Villager'/204, l='MpServer', x=58.54, y=67.00, z=288.27], EntityChicken['Chicken'/206, l='MpServer', x=59.79, y=73.00, z=322.10], EntityCreeper['Creeper'/219, l='MpServer', x=75.50, y=39.00, z=201.50], EntityPig['Pig'/220, l='MpServer', x=78.73, y=61.00, z=206.54], EntityZombie['Zombie'/221, l='MpServer', x=73.50, y=50.00, z=239.50], EntityVillager['Villager'/222, l='MpServer', x=77.67, y=64.00, z=244.06], EntityCreeper['Creeper'/223, l='MpServer', x=69.50, y=57.00, z=302.50], EntitySheep['Sheep'/224, l='MpServer', x=65.45, y=71.00, z=306.55], EntitySheep['Sheep'/225, l='MpServer', x=65.65, y=71.00, z=304.22], EntityPig['Pig'/232, l='MpServer', x=81.50, y=61.00, z=202.75], EntityBat['Bat'/234, l='MpServer', x=83.17, y=39.67, z=216.06], EntityPig['Pig'/237, l='MpServer', x=84.50, y=62.94, z=244.97], EntityVillager['Villager'/239, l='MpServer', x=78.48, y=66.00, z=272.27], EntityVillager['Villager'/240, l='MpServer', x=81.17, y=64.00, z=267.52], EntityVillager['Villager'/241, l='MpServer', x=80.47, y=65.00, z=283.60], EntityBat['Bat'/242, l='MpServer', x=82.71, y=12.00, z=297.86]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 983779896 bytes (938 MB) / 2225078272 bytes (2122 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAA	appleskin{1.0.9} [AppleSkin] (AppleSkin-mc1.10.2-1.0.9.jar) 
	UCHIJAAAA	Baubles{1.3.13} [Baubles] (Baubles-1.10.2-1.3.13.jar) 
	UCHIJAAAA	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
	UCHIJAAAA	cookingforblockheads{4.2.45} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.45.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.5.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.1x-3.6.5.jar) 
	UCHIJAAAA	gravestone{1.5.13} [Gravestone Mod] (gravestone-1.5.13.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.5.2} [JourneyMap] (journeymap-1.10.2-5.5.2.jar) 
	UCHIJAAAA	llor{1.1.1-mc[1.9-1.11]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.10.2.jar) 
	UCHIJAAAA	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.10.2-3.3.7.jar) 
	UCHIJAAAA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.7.10} [Storage Drawers] (StorageDrawers-1.10.2-3.7.10.jar) 
	UCHIJAAAA	thaumcraft{6.0.BETA3} [Thaumcraft] (Thaumcraft-1.10.2-6.0.BETA3.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.71' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: forge-12.18.3.2511
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz

**Comment by VocableWAZZAM** [comment]
Realized this was the wrong place to put this, sorry
