### ISSUE TITLE
CME server crash with Eldritch warden and Vampirism ghost

### ISSUE THREAD

**Issue by LemADEC** [Azanor/thaumcraft-5#679]
As of Thaumcraft-1.10.2-6.0.BETA6.jar and Vampirism-1.10.2-1.2.4.jar, server crashes with ConcurrentModificationException when a Vampirism ghost is inside a Eldritch warden aura.

```
Description: Ticking entity

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:586)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:343)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at de.teamlapen.vampirism.entity.EntityVampirism.func_70071_h_(EntityVampirism.java:176)
	at net.minecraft.world.World.func_72866_a(World.java:1967)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1937)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:586)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:343)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at de.teamlapen.vampirism.entity.EntityVampirism.func_70071_h_(EntityVampirism.java:176)
	at net.minecraft.world.World.func_72866_a(World.java:1967)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1937)

-- Entity being ticked --
Details:
	Entity Type: vampirism.ghost (de.teamlapen.vampirism.entity.EntityGhost)
	Entity ID: 393
	Entity Name: Ghost
	Entity's Exact location: 282,40, 72,00, 265,19
	Entity's Block location: World: (282,72,265), Chunk: (at 10,4,9 in 17,16; contains blocks 272,0,256 to 287,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0,08, -0,08, -0,12
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
```

Vampirism ghost will go invisible for 5 second when hit by an entity. This is done by applying the invisibility potion effect during the entity tick event.
Is Thaumcraft applying the aura potion effects at the same time but outside of the main thread?

Issue was reproduced in single player and on a dedicated server.

**Comment by LemADEC** [comment]
moved to https://github.com/Azanor/thaumcraft-beta/issues/350
