### ISSUE TITLE
Crashed when pressing esc while looking at the phial recipie in the thaumonomicon

### ISSUE THREAD

**Issue by numinx** [Azanor/thaumcraft-5#687]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.8.9.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LoadingPlugin (Skillable-beta-10.jar)
  BCModPlugin (backpacks 1.12.2 - 3.5.0.jar)
  llibrary (llibrary-1.7.9-1.12.2.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.5.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 5/4/18 8:48 AM
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: 1
	at thaumcraft.client.gui.GuiResearchPage.drawStackAt(GuiResearchPage.java:2035)
	at thaumcraft.client.gui.GuiResearchPage.drawCraftingPage(GuiResearchPage.java:1490)
	at thaumcraft.client.gui.GuiResearchPage.drawRecipe(GuiResearchPage.java:1040)
	at thaumcraft.client.gui.GuiResearchPage.drawPage(GuiResearchPage.java:465)
	at thaumcraft.client.gui.GuiResearchPage.genResearchBackground(GuiResearchPage.java:321)
	at thaumcraft.client.gui.GuiResearchPage.func_73863_a(GuiResearchPage.java:261)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callVoid(Reflector.java:636)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1454)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thaumcraft.client.gui.GuiResearchPage.drawStackAt(GuiResearchPage.java:2035)
	at thaumcraft.client.gui.GuiResearchPage.drawCraftingPage(GuiResearchPage.java:1490)
	at thaumcraft.client.gui.GuiResearchPage.drawRecipe(GuiResearchPage.java:1040)
	at thaumcraft.client.gui.GuiResearchPage.drawPage(GuiResearchPage.java:465)
	at thaumcraft.client.gui.GuiResearchPage.genResearchBackground(GuiResearchPage.java:321)
	at thaumcraft.client.gui.GuiResearchPage.func_73863_a(GuiResearchPage.java:261)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callVoid(Reflector.java:636)

-- Screen render details --
Details:
	Screen name: thaumcraft.client.gui.GuiResearchPage
	Mouse location: Scaled: (305, 223). Absolute: (610, 554)
	Screen size: Scaled: (603, 501). Absolute: (1206, 1001). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Numi_x'/2407623, l='MpServer', x=-822.36, y=104.00, z=-145.75]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 06 - quark_realistic, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (710,68,750), Chunk: (at 6,4,14 in 44,46; contains blocks 704,0,736 to 719,255,751), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Level time: 53438741 game time, 25363305 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 36 total; [EntitySnowVillager['Snow Villager'/2407845, l='MpServer', x=-781.49, y=110.00, z=-133.50], EntitySnowVillager['Snow Villager'/2407846, l='MpServer', x=-778.30, y=109.00, z=-126.50], EntityRabbit['Rabbit'/2407843, l='MpServer', x=-767.72, y=110.00, z=-137.91], EntityCow['Cow'/2407724, l='MpServer', x=-831.48, y=90.00, z=-69.55], EntityCow['Cow'/2407725, l='MpServer', x=-831.50, y=90.00, z=-68.56], EntityMinecartChest['Minecart with Chest'/2407727, l='MpServer', x=-830.50, y=21.06, z=-82.50], EntitySnowVillager['Snow Villager'/2407848, l='MpServer', x=-768.70, y=110.00, z=-135.50], EntityBasicHunter['Vampire Hunter'/2423592, l='MpServer', x=-781.18, y=109.00, z=-135.44], EntityCreeper['Creeper'/2464181, l='MpServer', x=-742.50, y=85.00, z=-95.50], EntityChicken['Chicken'/2407861, l='MpServer', x=-763.26, y=88.00, z=-66.11], EntityItem['item.item.egg'/2409021, l='MpServer', x=-847.24, y=105.00, z=-119.11], EntityPig['Pig'/2407737, l='MpServer', x=-883.50, y=118.00, z=-165.33], EntityPlayerSP['Numi_x'/2407623, l='MpServer', x=-822.36, y=104.00, z=-145.75], EntityRabbit['Rabbit'/2407837, l='MpServer', x=-779.70, y=109.00, z=-100.27], EntityChicken['Chicken'/2407833, l='MpServer', x=-771.21, y=109.00, z=-93.50], EntityItem['item.item.egg'/2407780, l='MpServer', x=-883.28, y=95.00, z=-83.03], EntityRabbit['Rabbit'/2407781, l='MpServer', x=-790.35, y=106.00, z=-180.45], EntityMinecartChest['Minecart with Chest'/2407782, l='MpServer', x=-842.50, y=40.06, z=-139.50], EntityRabbit['Rabbit'/2407776, l='MpServer', x=-847.80, y=105.00, z=-118.98], EntityChicken['Chicken'/2407777, l='MpServer', x=-847.78, y=105.00, z=-119.49], EntityChicken['Chicken'/2407778, l='MpServer', x=-883.89, y=95.00, z=-83.48], EntityBasicHunter['Vampire Hunter'/2417782, l='MpServer', x=-779.52, y=109.00, z=-128.18], EntityBasicHunter['Vampire Hunter'/2414450, l='MpServer', x=-763.82, y=110.00, z=-133.28], EntityChicken['Chicken'/2407749, l='MpServer', x=-896.10, y=97.00, z=-98.03], EntityChicken['Chicken'/2407744, l='MpServer', x=-887.51, y=95.00, z=-105.80], EntityChicken['Chicken'/2407746, l='MpServer', x=-889.50, y=97.00, z=-110.21], EntitySkeleton['Skeleton'/2414274, l='MpServer', x=-890.30, y=115.00, z=-154.53], EntityMinecartChest['Minecart with Chest'/2407747, l='MpServer', x=-837.50, y=31.06, z=-157.50], EntityRabbit['Rabbit'/2407756, l='MpServer', x=-844.51, y=94.00, z=-81.52], EntityMinecartChest['Minecart with Chest'/2407624, l='MpServer', x=-829.50, y=30.06, z=-150.50], EntityChicken['Chicken'/2407753, l='MpServer', x=-885.11, y=99.00, z=-118.33], EntityFireDragon['Fire Dragon'/2407755, l='MpServer', x=-861.27, y=9.38, z=-179.27], EntityRabbit['Rabbit'/2407767, l='MpServer', x=-818.66, y=108.00, z=-108.69], EntityMinecartChest['Minecart with Chest'/2407772, l='MpServer', x=-816.50, y=35.06, z=-118.50], EntityChicken['Chicken'/2407774, l='MpServer', x=-880.51, y=95.00, z=-74.79], EntityChicken['Chicken'/2407769, l='MpServer', x=-866.89, y=92.00, z=-68.67]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 817186472 bytes (779 MB) / 2804416512 bytes (2674 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.3.2676 Optifine OptiFine_1.12.2_HD_U_C9 82 mods loaded, 82 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version                  | Source                                          | Signature                                |
	|:------ |:------------------------ |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft                | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJA | mcp                      | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJA | FML                      | 8.0.99.99                | forge-1.12.2-14.23.3.2676.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                    | 14.23.3.2676             | forge-1.12.2-14.23.3.2676.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | codechickenlib           | 3.1.7.340                | CodeChickenLib-1.12.2-3.1.7.340-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | ancientwarfare           | 1.12.2-2.5.177           | ancientwarfare-1.12.2-2.5.177.jar               | None                                     |
	| UCHIJA | redstoneflux             | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJA | ancientwarfareautomation | 1.12.2-2.5.177           | ancientwarfare-1.12.2-2.5.177.jar               | None                                     |
	| UCHIJA | ancientwarfarenpc        | 1.12.2-2.5.177           | ancientwarfare-1.12.2-2.5.177.jar               | None                                     |
	| UCHIJA | ancientwarfarestructure  | 1.12.2-2.5.177           | ancientwarfare-1.12.2-2.5.177.jar               | None                                     |
	| UCHIJA | ancientwarfarevehicle    | 1.12.2-2.5.177           | ancientwarfare-1.12.2-2.5.177.jar               | None                                     |
	| UCHIJA | antiqueatlas             | 4.4.7                    | antiqueatlas-1.12.2-4.4.7.jar                   | None                                     |
	| UCHIJA | antiqueatlasoverlay      | 1.2                      | antiqueatlas-1.12.2-4.4.7.jar                   | None                                     |
	| UCHIJA | examplemod               | 1.0                      | antiqueatlas-1.12.2-4.4.7.jar                   | None                                     |
	| UCHIJA | crafttweaker             | 4.1.8                    | CraftTweaker2-1.12-4.1.8.jar                    | None                                     |
	| UCHIJA | mtlib                    | 3.0.4                    | MTLib-3.0.4.jar                                 | None                                     |
	| UCHIJA | modtweaker               | 4.0.10                   | modtweaker-4.0.10.jar                           | None                                     |
	| UCHIJA | jei                      | 4.9.1.175                | jei_1.12.2-4.9.1.175.jar                        | None                                     |
	| UCHIJA | appleskin                | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| UCHIJA | baubles                  | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHIJA | astralsorcery            | 1.8.9                    | astralsorcery-1.12.2-1.8.9.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJA | quark                    | r1.4-123                 | Quark-r1.4-123.jar                              | None                                     |
	| UCHIJA | skillable                | beta-10                  | Skillable-beta-10.jar                           | None                                     |
	| UCHIJA | autoreglib               | 1.3-17                   | AutoRegLib-1.3-17.jar                           | None                                     |
	| UCHIJA | backpacks16840           | 3.5.0                    | backpacks 1.12.2 - 3.5.0.jar                    | None                                     |
	| UCHIJA | bibliocraft              | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCHIJA | guideapi                 | 1.12-2.1.5-60            | Guide-API-1.12-2.1.5-60.jar                     | None                                     |
	| UCHIJA | bloodmagic               | 1.12.2-2.2.11-96         | BloodMagic-1.12.2-2.2.11-96.jar                 | None                                     |
	| UCHIJA | bonsaitrees              | 1.0.4                    | bonsaitrees-1.0.4-b71.jar                       | None                                     |
	| UCHIJA | thaumcraft               | 6.1.BETA11               | Thaumcraft-1.12.2-6.1.BETA11.jar                | None                                     |
	| UCHIJA | botania                  | r1.10-354                | Botania r1.10-354.jar                           | None                                     |
	| UCHIJA | chameleon                | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHIJA | chargers                 | 1.0.0                    | Chargers-1.12.2-1.0.0.1.jar                     | 58e787c8aafad8b327883f94d4fa544f936d7b01 |
	| UCHIJA | cofhcore                 | 4.4.1                    | CoFHCore-1.12.2-4.4.1.12-universal.jar          | None                                     |
	| UCHIJA | cofhworld                | 1.1.1                    | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCHIJA | cyclopscore              | 0.11.5                   | CyclopsCore-1.12.2-0.11.5.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJA | commoncapabilities       | 1.4.0                    | CommonCapabilities-1.12-1.4.0.jar               | None                                     |
	| UCHIJA | ctgui                    | 1.0.0                    | CraftTweaker2-1.12-4.1.8.jar                    | None                                     |
	| UCHIJA | crafttweakerjei          | 2.0.2                    | CraftTweaker2-1.12-4.1.8.jar                    | None                                     |
	| UCHIJA | creeperconfetti          | 1.4.2                    | creeperconfetti-1.4.2.jar                       | None                                     |
	| UCHIJA | diethopper               | 1.1                      | diethopper-1.1.jar                              | None                                     |
	| UCHIJA | foamflower               | 1.12.2-1.0.0.0-beta1     | foamflower-1.12.2-1.0.0.0-beta1.jar             | None                                     |
	| UCHIJA | enderpay                 | 1.12.2-1.0.1.0           | enderpay-1.12.2-1.0.1.0.jar                     | None                                     |
	| UCHIJA | ftblib                   | 5.0.2.10                 | FTBLib-5.0.2.10.jar                             | None                                     |
	| UCHIJA | ftbutilities             | 5.0.2.10                 | FTBUtilities-5.0.2.10.jar                       | None                                     |
	| UCHIJA | gravestone               | 1.0.14                   | GraveStone-1.12-Graves-1.0.14.jar               | None                                     |
	| UCHIJA | gravestone-extended      | 1.3.0b6                  | GraveStone-1.12.2-Extended-1.3.0b6.jar          | None                                     |
	| UCHIJA | hopperducts              | 1.5                      | hopperducts-mc1.12-1.5.jar                      | None                                     |
	| UCHIJA | llibrary                 | 1.7.9                    | llibrary-1.7.9-1.12.2.jar                       | None                                     |
	| UCHIJA | iceandfire               | 1.3.1                    | iceandfire-1.3.1-1.12.2.jar                     | None                                     |
	| UCHIJA | integrateddynamics       | 0.11.11                  | IntegratedDynamics-1.12.2-0.11.11.jar           | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJA | integrateddynamicscompat | 1.0.0                    | IntegratedDynamics-1.12.2-0.11.11.jar           | None                                     |
	| UCHIJA | integratedtunnels        | 1.5.5                    | IntegratedTunnels-1.12.2-1.5.5.jar              | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJA | integratedtunnelscompat  | 1.0.0                    | IntegratedTunnels-1.12.2-1.5.5.jar              | None                                     |
	| UCHIJA | inventorytweaks          | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | ironchest                | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                 | None                                     |
	| UCHIJA | jeresources              | 0.8.6.28                 | JustEnoughResources-1.12.2-0.8.6.28.jar         | None                                     |
	| UCHIJA | mantle                   | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| UCHIJA | mousetweaks              | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
	| UCHIJA | oreexcavation            | 1.4.118                  | OreExcavation-1.4.118.jar                       | None                                     |
	| UCHIJA | tconstruct               | 1.12.2-2.9.1.65          | TConstruct-1.12.2-2.9.1.65.jar                  | None                                     |
	| UCHIJA | oreshrubs                | 1.4.4                    | oreshrubs-1.4.4-1.12.2.jar                      | None                                     |
	| UCHIJA | thermalfoundation        | 2.4.1                    | ThermalFoundation-1.12.2-2.4.1.15-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | twilightforest           | 3.6.345                  | twilightforest-1.12.2-3.6.345-universal.jar     | None                                     |
	| UCHIJA | plustic                  | 6.4.0.0                  | plustic-6.4.0.0.jar                             | None                                     |
	| UCHIJA | quickleafdecay           | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar               | None                                     |
	| UCHIJA | randomthings             | 4.1.5                    | RandomThings-MC1.12.2-4.1.5.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJA | roguelike                | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar              | None                                     |
	| UCHIJA | spartanshields           | 1.4.1                    | SpartanShields-1.12.2-1.4.1.jar                 | None                                     |
	| UCHIJA | spartanweaponry          | beta 1.1.2               | SpartanWeaponry-1.12.2-beta-1.1.2.jar           | None                                     |
	| UCHIJA | stg                      | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                            | None                                     |
	| UCHIJA | storagedrawers           | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.6.jar                 | None                                     |
	| UCHIJA | theoneprobe              | 1.4.22                   | theoneprobe-1.12-1.4.22.jar                     | None                                     |
	| UCHIJA | tinkertoolleveling       | 1.12-1.0.3.DEV.56fac4f   | TinkerToolLeveling-1.12-1.0.3.jar               | None                                     |
	| UCHIJA | topaddons                | 1.12.2-1.6.0             | topaddons-1.12.2-1.6.0.jar                      | None                                     |
	| UCHIJA | uppers                   | 0.0.4                    | Uppers-0.0.4.jar                                | None                                     |
	| UCHIJA | vampirism                | 1.4.0                    | Vampirism-1.12.2-1.4.0.jar                      | None                                     |
	| UCHIJA | teamlapen-lib            | 1.4.0                    | Vampirism-1.12.2-1.4.0.jar                      | None                                     |
	| UCHIJA | vending                  | 1.12.2-3.0.1.1           | vending-1.12.2-3.0.1.1.jar                      | None                                     |
	| UCHIJA | weaponlevels             | 2.1.2                    | weaponlevels-2.1.2.jar                          | None                                     |
	| UCHIJA | weirdinggadget           | 1.0                      | weirdinggadget-1.12.2-2.0.5-universal.jar       | None                                     |
	| UCHIJA | yoyos                    | 1.12.2-1.2.2.20          | yoyos_1.12.2-1.2.2.20.jar                       | None                                     |

	Loaded coremods (and transformers): 
AstralCore (astralsorcery-1.12.2-1.8.9.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (Skillable-beta-10.jar)
  vazkii.skillable.base.asm.ClassTransformer
BCModPlugin (backpacks 1.12.2 - 3.5.0.jar)
  brad16840.core.ClassTransformer
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.1.5.jar)
  lumien.randomthings.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 6450'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Launched Version: forge-14.23.3.2676
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 6450 GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU E8400 @ 3.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C9
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.1008
	OpenGlRenderer: AMD Radeon HD 6450
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2

**Comment by MainFreak** [comment]
Issues of the Thaumcraft 6 Beta belong [here](https://github.com/Azanor/thaumcraft-beta/issues)
