### ISSUE TITLE
Thaumcraft 5 not working with any optifine

### ISSUE THREAD

**Issue by SoldierKucha** [Azanor/thaumcraft-5#96]
[00:00:29] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[00:00:29] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[00:00:29] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[00:00:29] [main/INFO] [FML]: Forge Mod Loader version 11.14.3.1529 for Minecraft 1.8 loading
[00:00:29] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_51, running on Windows 8:amd64:6.2, installed at I:\Program Files\Java\jre7
[00:00:30] [main/INFO] [FML]: Loading tweaker me.guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.1.1 (1).jar
[00:00:30] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.8.0_HD_U_B6.jar
[00:00:30] [main/WARN] [FML]: The coremod thaumcraft.loader.ThaumcraftLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:00:30] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:00:30] [main/INFO] [LaunchWrapper]: Loading tweak class name me.guichaguri.betterfps.tweaker.BetterFpsTweaker
[00:00:30] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[00:00:30] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[00:00:30] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:00:30] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:00:30] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[00:00:30] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: acceptOptions
[00:00:30] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: injectIntoClassLoader
[00:00:30] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ClassTransformer
[00:00:30] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine URL: file:/I:/Users/Администратор/Desktop/MultiMC/instances/Thaum/minecraft/mods/OptiFine_1.8.0_HD_U_B6.jar
[00:00:30] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ZIP file: java.util.zip.ZipFile@61d93674
[00:00:30] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:00:36] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[00:00:36] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[00:00:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:00:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:00:39] [main/INFO] [LaunchWrapper]: Calling tweak class me.guichaguri.betterfps.tweaker.BetterFpsTweaker
[00:00:39] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[00:00:42] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[00:00:42] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[00:00:42] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: getLaunchArguments
[00:00:42] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[00:00:43] [main/INFO] [me.guichaguri.betterfps.transformers.EventTransformer]: Patching Game Start...
[00:00:46] [Client thread/INFO]: Setting user: <PROFILE NAME>
[00:00:54] [Client thread/INFO] [me.guichaguri.betterfps.transformers.EventTransformer]: Patching Key Event...
[00:00:54] [Client thread/INFO]: LWJGL Version: 2.9.1
[OptiFine] 
[OptiFine] OptiFine_1.8_HD_U_B6
[OptiFine] Thu Nov 12 00:00:56 NOVT 2015
[OptiFine] OS: Windows 8 (amd64) version 6.2
[OptiFine] Java: 1.7.0_51, Oracle Corporation
[OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[OptiFine] LWJGL: 2.9.1
[OptiFine] OpenGL: Intel(R) HD Graphics 3000, version 3.1.0 - Build 9.17.10.4229, Intel
[OptiFine] OpenGL Version: 3.1
[OptiFine] OpenGL Fancy fog: Not available (GL_NV_fog_distance)
[OptiFine] Maximum texture size: 8192x8192
[OptiFine] Checking for new version
[00:00:56] [Client thread/INFO] [FML]: Forge Mod Loader has detected optifine OptiFine_1.8_HD_U_B6, enabling compatibility features
[00:00:56] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[00:00:56] [Client thread/INFO] [FML]: MinecraftForge v11.14.3.1529 Initialized
[00:00:56] [Client thread/INFO] [FML]: Replaced 204 ore recipies
[OptiFine] (Reflector) Class not present: ModLoader
[OptiFine] (Reflector) Class not present: net.minecraft.src.FMLRenderAccessLibrary
[OptiFine] (Reflector) Class not present: LightCache
[OptiFine] (Reflector) Class not present: BlockCoord
[OptiFine] Version found: D5
[00:00:58] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[00:00:58] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[00:00:58] [Client thread/INFO] [FML]: Searching I:\Users\Администратор\Desktop\MultiMC\instances\Thaum\minecraft\mods for mods
[00:00:58] [Client thread/INFO] [FML]: Also searching I:\Users\Администратор\Desktop\MultiMC\instances\Thaum\minecraft\mods\1.8 for mods
[00:01:06] [Client thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[00:01:07] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, Thaumcraft, Baubles] at CLIENT
[00:01:07] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, Thaumcraft, Baubles] at SERVER
[00:01:09] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Thaumcraft, FMLFileResourcePack:Baubles
[00:01:09] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[00:01:09] [Client thread/INFO] [FML]: Found 384 ObjectHolder annotations
[00:01:09] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[00:01:09] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[00:01:09] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[00:01:10] [Client thread/INFO] [BetterFps]: Patching Minecraft using Riven's "Half" Algorithm
[00:01:13] [Client thread/INFO] [FML]: Applying holder lookups
[00:01:13] [Client thread/INFO] [FML]: Holder lookups applied
[00:01:13] [Client thread/INFO] [FML]: Injecting itemstacks
[00:01:13] [Client thread/INFO] [FML]: Itemstack injection complete
[OptiFine] *** Reloading textures ***
[OptiFine] Resource packs: Default
[00:01:14] [Sound Library Loader/INFO]: Starting up SoundSystem...
[00:01:14] [Thread-9/INFO]: Initializing LWJGL OpenAL
[00:01:14] [Thread-9/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[00:01:15] [Thread-9/INFO]: OpenAL initialized.
[00:01:15] [Sound Library Loader/INFO]: Sound engine started
[00:01:31] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:571]: ---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 11/12/15 12:01 AM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraft.client.renderer.texture.TextureMap.<init>(Ljava/lang/String;Z)V
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.7.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1014741488 bytes (967 MB) / 1338507264 bytes (1276 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx2048m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1529 Optifine OptiFine_1.8_HD_U_B6 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1529-universal.jar) 
	UCH	Forge{11.14.3.1529} [Minecraft Forge] (forge-1.8-11.14.3.1529-universal.jar) 
	UCH	Baubles{1.1.1.0} [Baubles] (Baubles-1.8-1.1.1.0.jar) 
	UCH	Thaumcraft{5.0.3} [Thaumcraft] (Thaumcraft-1.8-5.0.3.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8-5.0.3.jar)
  
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.4229, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
[00:01:31] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:571]: #@!@# Game crashed! Crash report saved to: #@!@# I:\Users\Admin\Desktop\MultiMC\instances\Thaum\minecraft\crash-reports\crash-2015-11-12_00.01.30-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Game exited with exitcode -1.

**Comment by Azanor** [comment]
Some versions of optifine do work, though don't ask me exactly which ones. Apart from that this isn't really a problem on the TC side, so closing.
